# Generated by Django 4.1.7 on 2023-04-01 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coti', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datos',
            name='correo',
        ),
    ]
